services:
  postgres:
    image: postgres:14-alpine
    container_name: postgresql
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/database/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'

  minio:
    image: bitnami/minio:2023.2.22
    container_name: minio
    restart: always
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER="minio"
      - MINIO_ROOT_PASSWORD="miniosecret"
      - MINIO_DEFAULT_BUCKETS="mlflow"
    ports:
      - '9000:9000'
      - '9001:9001'

volumes:
  minio_data:
    driver: local
  postgres_data:
    driver: local

    